//Mảng dữ liệu thẻ
let elementArr = [
  {
    id: "comment",
    name: "<!--(comment)-->",
    meaning: "Bình luận",
    example: "<!--This can be viewed in the HTML part of a document-->",
    browser: '<!--This can be viewed in the HTML part of a document-->',
  },
  {
    id: "a-tag",
    name: "<a>",
    meaning: "Anchor - Mỏ neo - Dẫn đường link",
    example: '<a href="/codic.html"> Visit Our Site</a>',
    browser: '<a href="/codic.html"> Visit Our Site</a>',
  },
  {
    id: "b-tag",
    name: "<b>",
    meaning: "Bold - In đậm",
    example: "<b>Example</b>",
    browser: '<b>Example</b>',
  },
  {
    id: "big-tag",
    name: "<big>",
    meaning: "Big (text) - Cỡ chữ to",
    example: "<big>Example</big>",
    browser: '<big>Example</big>',
  },
  {
    id: "body-tag",
    name: "<body>",
    meaning: "Body of HTML document - Thân bài",
    example: "<body>The content of your HTML page</body>",
    browser: '',
  },
  {
    id: "br-tag",
    name: "<br>",
    meaning: "Line break - Xuống dòng",
    example: "The contents of your page<br>The contents of your page",
    browser: '',
  },
  {
    id: "center-tag",
    name: "<center>",
    meaning: "Center - Căn giữa",
    example: "<center>This will center your contents</center>",
    browser: '',
  },
  {
    id: "dd-tag",
    name: "<dd>",
    meaning: "Definition description - Định nghĩa",
    example: "<dd>Definition of the term</dd>",
    browser: '',
  },
  {
    id: "dl-tag",
    name: "<dl>",
    meaning: "Definition list - Danh sách định nghĩa",
    example: "<dl>\n<dt>Definition Term</dt>\n<dd>Definition of the term</dd>\n</dl>",
    browser: '',
  },
  {
    id: "em-tag",
    name: "<em>",
    meaning: "Emphasis - In đậm và nhấn mạnh",
    example: "This is an <em>Example</em> of using the emphasis tag",
    browser: '',
  },
  {
    id: "font-tag",
    name: "<font>",
    meaning: "Font - Định dạng",
    example: '<font face="Times New Roman">Example</font>',
    browser: '',
  },
  {
    id: "form-tag",
    name: "<form>",
    meaning: "Form - Biểu mẫu",
    example: '<form action="/action_page.php"> \n<label for ="fname">First name:</label><br> \n<input type="text" id="fname" name="fname" value="John"><br> \n<label for="lname">Last name:</label><br> \n<input type="text" id="lname" name="lname" value="Doe"><br><br> \n<input type="submit" value="Submit"> \n</form>',
    browser: '',
  },
  { id: "heading-tag",
    name: "<h1>,<h2>,<h3>,<h4>,<h5>,<h6>",
    meaning: "Heading - Đầu mục",
    example: "<h1>Heading 1 Example</h1>\n<h2>Heading 2 Example</h2>\n<h3>Heading 3 Example</h3>\n<h4>Heading 4 Example</h4>\n<h5>Heading 5 Example</h5>\n<h6>Heading 6 Example</h6>",
    browser: '',
  },
  { 
    id: "head-tag",
    name: "<head>",
    meaning: "Heading of HTML document - Phần mở đầu của HTML",
    example: "<head>Contains elements describing the document</head>",
    browser: '',
  },
  { id: "horizontal-rule",
    name: "<hr/>",
    meaning: "Horizontal rule - Kẻ ngang từ điểm bắt đầu đến điểm kết thúc",
    example: "<hr/>",
    browser: '',
  },
  {
    id: "hypertext-markup-language",
    name: "<html>",
    meaning: "Hypertext markup language - Ngôn ngữ đánh dấu siêu văn bản",
    example: "<html>\n<head>\n<meta>\n<title>Title of your web page</title>\n</head>\n<body>HTML web page contents\n</body>\n</html>",
    browser: '',
  },
  { id: "italic",
    name: "<i>",
    meaning: "Italic - In nghiêng",
    example: "<i>Example</i>",
    browser: '',
  },
  { id: "image",
    name: "<img>",
    meaning: "Image - Chèn ảnh",
    example: '<img src="Earth.gif" width="41" height="41" border="0" alt="text describing the image" />',
    browser: '',
  },
  {
    id: "input",
    name: "<input>",
    meaning: "Input field - ô nhập thông tin",
    example: '<form method=post action="/cgibin/example.cgi">\n<input type="text" size="10"\nmaxlength="30">\n<input type="Submit" value="Submit">\n</form>',
    browser: '',
  },
  { 
  id: "list-item",
  name: "<li>",
  meaning: "List item - Danh sách liệt kê",
  example: '<menu>\n<li type="disc">List item 1</li>\n<li type="circle">List item 2</li>\n<li type="square">List item 3</li>\n</MENU>',
  browser: '',
  },
  { 
    id: "link",
    name: "<link>",
    meaning: "Link - đường dẫn",
    example: '<head>\n<link rel="stylesheet" type="text/css"\nhref="style.css" />\n</head>',
    browser: '',
  },
  { 
    id: "menu",
    name: "<menu>",
    meaning: "menu - Menu - Bảng kê",
    example: '<menu>\n<li type="disc">List item 1</li>\n<li type="circle">List item 2</li>\n<li type="square">List item 3</li>\n</menu>',
    browser: '',
  },
  { 
    id: "meta",
    name: "<meta>",
    meaning: "Meta - Thông tin về dữ liệu",
    example: '<meta name="Description" content="Description of your site">\n<meta name="keywords" content="keywords describing your site">',
    browser: '',
  },
  { 
    id: "ordered-list",
    name: "<ol>",
    meaning: "Ordered list - Danh sách liệt kê theo thứ tự",
    example: '<ol>\n<li>List item 1</li>\n<li>List item 2</li>\n<li>List item 3</li>\n<li>List item 4</li>\n</ol>',
    browser: '',
  },
  { 
    id: "option",
    name: "<option>",
    meaning: "Listbox option - Hộp tuỳ chọn",
    example: '<form method=post action="/cgi- bin/example.cgi">\n<center>\nSelect an option:\n<select>\n<option>option 1</option>\n<option selected>option 2</option>\n<option>option 3</option>\n<option>option 4</option>\n<option>option 5</option>\n<option>option 6</option>\n</select><br>\n</center>\n</form>',
    browser: '',
  },
  { 
    id: "paragraph",
    name: "<p>",
    meaning: "Paragraph - Đoạn văn",
    example: 'This is an example displaying the use of the paragraph tag. <p> This will create a line break and a space between lines.<br>\nAttributes: Example 1:<br>\n<br>\n<p align="left">\nThis is an example<br> displaying the use<br>\nof the paragraph tag.<br>\n<br>\nExample 2:<br>\n<br>\n<p align="right"> This is an example<br> displaying the use<br>\nof the paragraph tag.<br>\n<br>\nExample 3:<br>\n<br>\n<p align="center"> This is an example<br> displaying the use<br> of the paragraph tag.',
    browser: '',
  },
  { 
    id: "strong",
    name: "<strong>",
    meaning: "Strong emphasis - In đậm và nhấn mạnh",
    example: '<strong>Example</strong>',
    browser: '',
  },
  { 
    id: "table",
    name: "<table>",
    meaning: "Table - Bảng",
    example: '<table border="4" cellpadding="2" cellspacing="2" width="100%">\n<tr>\n<td>Column 1</td>\n<td>Column 2</td>\n</tr>\n</table>',
    browser: '',
  },
  { 
    id: "table-data",
    name: "<td>",
    meaning: "Table data - Thông tin từng ô trong bảng",
    example: '<table border="2" cellpadding="2" cellspacing="2" width="100%">\n<tr>\n<td>Column 1</td>\n<td>Column 2</td>\n</tr>\n</table>',
    browser: '',
  },
  { 
    id: "table-header",
    name: "<th>",
    meaning: "Table header - Đầu mục của bảng",
    example: '<div align="center">\n<table>\n<tr>\n<th>Column 1</th>\n<th>Column 2</th>\n<th>Column 3</th>\n</tr>\n<tr>\n<td>Row 2</td>\n<td>Row 2</td>\n<td>Row 2</td>\n</tr>\n<tr>\n<td>Row 3</td>\n<td>Row 3</td>\n<td>Row 3</td>',
    browser: '',
  },
  { 
    id: "title",
    name: "<title>",
    meaning: "Document title - Tiêu đề",
    example: '<title>Title of your HTML page</title>',
    browser: '',
  },
  { 
    id: "table-row",
    name: "<tr>",
    meaning: "Table row - Hàng của bảng",
    example: '<table border="2" cellpadding="2" cellspacing="2" width="100%">\n<tr>\n<td>Column 1</td>\n<td>Column 2</td>\n</tr>\n</table>',
    browser: '',
  },
  { 
    id: "underline",
    name: "<u>",
    meaning: "Underline - gạch chân",
    example: '<u>Example</u>',
    browser: '',
  },
  { 
    id: "unordered-list",
    name: "<ul>",
    meaning: "Unordered list - Danh sách không theo thứ tự",
    example: 'Example 1:<br>\n<br>\n<ul>\n<li>List item 1</li>\n<li>List item 2</li>\n</ul>\n<br>\nExample 2:<br>\n<ul type="disc">\n<li>List item 1</li>\n<li>List item 2</li>\n<ul type="circle">\n<li>List item 3</li>\n<li>List item 4</li>\n</ul>\n</ul>',
    browser: '',
  },
]

// xuất khẩu lao động object này
export {elementArr};