//Mảng dữ liệu thẻ html
let elementArr = [
  {
    id: "comment",
    name: "<!--(comment)-->",
    meaning: "Bình luận",
    example: "<!--This can be viewed in the HTML part of a document-->",
    browser: '',
    ahihi: "hidden",
  },
  {
    id: "a-tag",
    name: "<a>",
    meaning: "Anchor - Mỏ neo - Dẫn đường link",
    example: '<a href="/index.html"> Visit Our Site</a>',
    browser: '<a href="/index.html"> Visit Our Site</a>',
  },
  {
    id: "b-tag",
    name: "<b>",
    meaning: "Bold - In đậm",
    example: "<b>Example</b>",
    browser: '<b>Example</b>',
  },
  {
    id: "big-tag",
    name: "<big>",
    meaning: "Big (text) - Cỡ chữ to",
    example: "<big>Example</big>",
    browser: '<big>Example</big>',
  },
  {
    id: "body-tag",
    name: "<body>",
    meaning: "Body of HTML document - Thân bài",
    example: "<body>The content of your HTML page</body>",
    browser: '',
  },
  {
    id: "br-tag",
    name: "<br>",
    meaning: "Line break - Xuống dòng",
    example: "The contents of your page<br>The contents of your page",
    browser: '',
  },
  {
    id: "center-tag",
    name: "<center>",
    meaning: "Center - Căn giữa",
    example: "<center>This will center your contents</center>",
    browser: '',
  },
  {
    id: "dd-tag",
    name: "<dd>",
    meaning: "Definition description - Định nghĩa",
    example: "<dd>Definition of the term</dd>",
    browser: '',
  },
  {
    id: "dl-tag",
    name: "<dl>",
    meaning: "Definition list - Danh sách định nghĩa",
    example: "<dl>\n<dt>Definition Term</dt>\n<dd>Definition of the term</dd>\n</dl>",
    browser: '',
  },
  {
    id: "em-tag",
    name: "<em>",
    meaning: "Emphasis - In đậm và nhấn mạnh",
    example: "This is an <em>Example</em> of using the emphasis tag",
    browser: '',
  },
  {
    id: "font-tag",
    name: "<font>",
    meaning: "Font - Định dạng",
    example: '<font face="Times New Roman">Example</font>',
    browser: '',
  },
  {
    id: "form-tag",
    name: "<form>",
    meaning: "Form - Biểu mẫu",
    example: '<form action="/action_page.php"> \n<label for ="fname">First name:</label><br> \n<input type="text" id="fname" name="fname" value="John"><br> \n<label for="lname">Last name:</label><br> \n<input type="text" id="lname" name="lname" value="Doe"><br><br> \n<input type="submit" value="Submit"> \n</form>',
    browser: '',
  },
  {
    id: "heading-tag",
    name: "<h1> => <h6>",
    meaning: "Heading - Đầu mục",
    example: "<h1>Heading 1 Example</h1>\n<h2>Heading 2 Example</h2>\n<h3>Heading 3 Example</h3>\n<h4>Heading 4 Example</h4>\n<h5>Heading 5 Example</h5>\n<h6>Heading 6 Example</h6>",
    browser: '',
  },
  {
    id: "head-tag",
    name: "<head>",
    meaning: "Heading of HTML document - Phần mở đầu của HTML",
    example: "<head>Contains elements describing the document</head>",
    browser: '',
  },
  {
    id: "horizontal-rule",
    name: "<hr/>",
    meaning: "Horizontal rule - Kẻ ngang từ điểm bắt đầu đến điểm kết thúc",
    example: "<hr/>",
    browser: '',
  },
  {
    id: "hypertext-markup-language",
    name: "<html>",
    meaning: "Hypertext markup language - Ngôn ngữ đánh dấu siêu văn bản",
    example: "<html>\n<head>\n<meta>\n<title>Title of your web page</title>\n</head>\n<body>HTML web page contents\n</body>\n</html>",
    browser: '',
  },
  {
    id: "italic",
    name: "<i>",
    meaning: "Italic - In nghiêng",
    example: "<i>Example</i>",
    browser: '',
  },
  {
    id: "image",
    name: "<img>",
    meaning: "Image - Chèn ảnh",
    example: '<img src="Earth.gif" width="41" height="41" border="0" alt="text describing the image" />',
    browser: '',
  },
  {
    id: "input",
    name: "<input>",
    meaning: "Input field - ô nhập thông tin",
    example: '<form method=post action="/cgibin/example.cgi">\n<input type="text" size="10"\nmaxlength="30">\n<input type="Submit" value="Submit">\n</form>',
    browser: '',
  },
  {
    id: "list-item",
    name: "<li>",
    meaning: "List item - Danh sách liệt kê",
    example: '<menu>\n<li type="disc">List item 1</li>\n<li type="circle">List item 2</li>\n<li type="square">List item 3</li>\n</MENU>',
    browser: '',
  },
  {
    id: "link",
    name: "<link>",
    meaning: "Link - đường dẫn",
    example: '<head>\n<link rel="stylesheet" type="text/css"\nhref="style.css" />\n</head>',
    browser: '',
    ahihi: "hidden",
  },
  {
    id: "menu",
    name: "<menu>",
    meaning: "menu - Menu - Bảng kê",
    example: '<menu>\n<li type="disc">List item 1</li>\n<li type="circle">List item 2</li>\n<li type="square">List item 3</li>\n</menu>',
    browser: '',
  },
  {
    id: "meta",
    name: "<meta>",
    meaning: "Meta - Thông tin về dữ liệu",
    example: '<meta name="Description" content="Description of your site">\n<meta name="keywords" content="keywords describing your site">',
    browser: '',
    ahihi: "hidden",
  },
  {
    id: "ordered-list",
    name: "<ol>",
    meaning: "Ordered list - Danh sách liệt kê theo thứ tự",
    example: '<ol>\n<li>List item 1</li>\n<li>List item 2</li>\n<li>List item 3</li>\n<li>List item 4</li>\n</ol>',
    browser: '',
  },
  {
    id: "option",
    name: "<option>",
    meaning: "Listbox option - Hộp tuỳ chọn",
    example: '<form method=post action="/cgi- bin/example.cgi">\n<center>\nSelect an option:\n<select>\n<option>option 1</option>\n<option selected>option 2</option>\n<option>option 3</option>\n<option>option 4</option>\n<option>option 5</option>\n<option>option 6</option>\n</select><br>\n</center>\n</form>',
    browser: '',
  },
  {
    id: "paragraph",
    name: "<p>",
    meaning: "Paragraph - Đoạn văn",
    example: 'This is an example displaying the use of the paragraph tag. <p> This will create a line break and a space between lines.',
    browser: '',
  },
  {
    id: "strong",
    name: "<strong>",
    meaning: "Strong emphasis - In đậm và nhấn mạnh",
    example: '<strong>Example</strong>',
    browser: '',
  },
  {
    id: "table",
    name: "<table>",
    meaning: "Table - Bảng",
    example: '<table border="4" cellpadding="2" cellspacing="2" width="100%">\n<tr>\n<td>Column 1</td>\n<td>Column 2</td>\n</tr>\n</table>',
    browser: '',
  },
  {
    id: "table-data",
    name: "<td>",
    meaning: "Table data - Thông tin từng ô trong bảng",
    example: '<table border="2" cellpadding="2" cellspacing="2" width="100%">\n<tr>\n<td>Column 1</td>\n<td>Column 2</td>\n</tr>\n</table>',
    browser: '',
  },
  {
    id: "table-header",
    name: "<th>",
    meaning: "Table header - Đầu mục của bảng",
    example: '<div align="center">\n<table>\n<tr>\n<th>Column 1</th>\n<th>Column 2</th>\n</tr>\n<tr>\n<td>Row 2</td>\n<td>Row 2</td>\n</tr>\n<tr>\n<td>Row 3</td>\n<td>Row 3</td>',
    browser: '',
  },
  {
    id: "title",
    name: "<title>",
    meaning: "Document title - Tiêu đề",
    example: '<title>Title of your HTML page</title>',
    browser: '',
    ahihi: "hidden",
  },
  {
    id: "table-row",
    name: "<tr>",
    meaning: "Table row - Hàng của bảng",
    example: '<table border="2" cellpadding="2" cellspacing="2" width="100%">\n<tr>\n<td>Column 1</td>\n<td>Column 2</td>\n</tr>\n</table>',
    browser: '',
  },
  {
    id: "underline",
    name: "<u>",
    meaning: "Underline - gạch chân",
    example: '<u>Example</u>',
    browser: '',
  },
  {
    id: "unordered-list",
    name: "<ul>",
    meaning: "Unordered list - Danh sách không theo thứ tự",
    example: 'Example 1:<br>\n<br>\n<ul>\n<li>List item 1</li>\n<li>List item 2</li>\n<li>List item 3</li>\n</ul>',
    browser: '',
  },
]
// xuất khẩu lao động object này
export {elementArr};

// mảng dữ liệu thẻ css
let cssArr = [
  {
    name: "align-items",
    meaning: "",
    definition: "Căn chỉnh các thẻ con trong flexbox",
    example: "div {display: flex;align-items: center;}"
  },
  {
    name: "align-self",
    meaning: "",
    definition: "Căn chỉnh các thẻ con được chọn trong flexbox",
    example: "#myBlueDiv {\nalign-self: center;\n}"
  },
  {
    name: "background-color",
    meaning: "màu nền",
    definition: "Specifies the background color of an element",
    example: "body {\nbackground-color: coral;\n}"
  },
  {
    name: "background-image",
    meaning: "ảnh nền",
    definition: "Specifies one or more background images for an element",
    example: "body {\nbackground-image: linear-gradient(45deg, red, green);\n}",
  },
  {
    name: "border",
    meaning: "viền",
    definition: "A shorthand property for border-width, border-style and border-color",
    example: "h1 {\nborder: 5px solid red;\n}",
  },
  {
    name: "box-sizing",
    meaning: "",
    definition: "Defines how the width and height of an element are calculated: should they include padding and borders, or not",
    example: "#example1 {\nbox-sizing: border-box;\n}",
  },
  {
    name: "color",
    meaning: "",
    definition: "Sets the color of text",
    example: "body {color: red;}",
  },
  {
    name: "column-width",
    meaning: "",
    definition: "Specifies the column width",
    example: "div {\ncolumn-width: 100px;\n}",
  },
  {
    name: "display",
    meaning: "hiển thị",
    definition: "Specifies how a certain HTML element should be displayed",
    example: "p.ex2 {display: inline;}",
  },
  {
    name: "flex-direction",
    meaning: "",
    definition: "Specifies the direction of the flexible items",
    example: "div {\ndisplay: flex;\nflex-direction: row-reverse;\n}",
  },
  {
    name: "flex-wrap",
    meaning: "",
    definition: "Specifies whether the flexible items should wrap or not",
    example: "div {\ndisplay: flex;  \nflex-wrap: wrap;\n}",
  },
  {
    name: "font-family",
    meaning: "phông chữ",
    definition: "Specifies whether the flexible items should wrap or not",
    example: "div {\ndisplay: flex;  \nflex-wrap: wrap;\n}",
  },
  {
    name: "font-size",
    meaning: "cỡ chữ",
    definition: "Specifies the font size of text",
    example: "div {\nfont-size: 15px;\n}",
  },
  {
    name: "font-weight",
    meaning: "độ dày chữ",
    definition: "Specifies the weight of a font",
    example: "div {\nfont-weight: bold;\n}",
  },
  {
    name: "grid",
    meaning: "",
    definition: "A shorthand property for the grid-template-rows, grid-template-columns, grid-template-areas, grid-auto-rows, grid-auto-columns, and the grid-auto-flow properties",
    example: ".grid-container {\ndisplay: grid;\ngrid: 150px / auto auto auto;\n}",
  },
  {
    name: "grid-template-columns",
    meaning: "",
    definition: "Specifies the size of the columns, and how many columns in a grid layout",
    example: ".grid-container {\ndisplay: grid;\ngrid-template-columns: auto auto auto auto;\n}",
  },
  {
    name: "grid-template-rows",
    meaning: "",
    definition: "Specifies the size of the rows in a grid layout",
    example: ".grid-container {\ndisplay: grid;\ngrid-template-rows: 100px 300px;\n}",
  },
  {
    name: "height",
    meaning: "chiều cao",
    definition: "Sets the height of an element",
    example: "div.a {\nheight: auto;\nborder: 1px solid black;\n}",
  },
  {
    name: "justify-content",
    meaning: "xếp hàng ngang nội dung",
    definition: "Specifies the alignment between the items inside a flexible container when the items do not use all available space",
    example: "div {\ndisplay: flex;\njustify-content: center;\n}",
  },
  {
    name: "margin",
    meaning: "khoảng trống ngoài viền",
    definition: "Sets all the margin properties in one declaration",
    example: "p {\nmargin: 35px;\n}",
  },
  {
    name: "max-width",
    meaning: "chiều rộng tối đa",
    definition: "Sets the maximum width of an element",
    example: "p.ex1 {\nmax-width: 150px;\n}",
  },
  {
    name: "min-width",
    meaning: "chiều rộng tối thiểu",
    definition: "Sets the minimum width of an element",
    example: "p.ex1 {\nmax-width: 500px;\n}",
  },
  {
    name: "max-height",
    meaning: "chiều cao tối đa",
    definition: "Sets the maximum height of an element",
    example: "p.ex1 {\nmax-height: 50px;\n}",
  },
  {
    name: "min-height",
    meaning: "chiều cao tối thiểu",
    definition: "Sets the minimum height of an element",
    example: "p.ex1 {\nmin-height: 100px;\n}",
  },
  {
    name: "order",
    meaning: "thứ tự",
    definition: "Căn chỉnh vị trí một thẻ con, so với những thẻ còn lại",
    example: "div#myRedDIV {order: 2;}",
  },
  {
    name: "overflow",
    meaning: "tràn",
    definition: "Specifies what happens if content overflows an element's box",
    example: "div.ex1 {\noverflow: scroll;\n}",
  },
  {
    name: "overflow-x",
    meaning: "tràn theo trục x",
    definition: "Specifies whether or not to clip the left/right edges of the content, if it overflows the element's content area",
    example: "div.ex1 {\noverflow-x: hidden;\n}",
  },
  {
    name: "overflow-y",
    meaning: "tràn theo trục y",
    definition: "Specifies whether or not to clip the top/bottom edges of the content, if it overflows the element's content area",
    example: "div.ex1 {\noverflow-x: hidden;\n}",
  },
  {
    name: "padding",
    meaning: "đệm",
    definition: "A shorthand property for all the padding-* properties",
    example: "p {\npadding: 35px;\n}",
  },
  {
    name: "position",
    meaning: "vị trí",
    definition: "Specifies the type of positioning method used for an element (static, relative, absolute or fixed)",
    example: "h2 {\nposition: absolute;\nleft: 100px;\ntop: 150px;\n}",
  },
  {
    name: "text-align",
    meaning: "căn chỉnh văn bản",
    definition: "căn chỉnh chiều ngang của văn bản",
    example: "h2 {\nposition: absolute;\nleft: 100px;\ntop: 150px;\n}",
  },
  {
    name: "transition",
    meaning: "",
    definition: "A shorthand property for all the transition-* properties",
    example: "div {\nwidth: 100px;\ntransition: width 2s;\n}\ndiv:hover {\nwidth: 300px;\n}",
  },
  {
    name: "width",
    meaning: "chiều rộng",
    definition: "Sets the width of an element",
    example: "div.b {\nwidth: 150px;\nborder: 1px solid black;\n}",
  },
  {
    name: "z-index",
    meaning: "trục z",
    definition: "Sets the stack order of a positioned element",
    example: "img {\nposition: absolute;\nleft: 0px;\ntop: 0px;\nz-index: -1;\n}",
  },
]

export {cssArr};


